### ISSUE TITLE
Test input

### ISSUE THREAD

**Issue by DavidHaslam** [ninjaaron/ivsort.py#1]
Please could you post a test input file (a suitable unsorted list of pointed words) so that users can compare the output of your script to what they obtain from standard sorts.

David

**Comment by ninjaaron** [comment]
Thanks for the input David! I've created a list of test words. A couple of them are made up, but they are according to real Hebrew morphological patterns. I have to admit that the gnu `sort` utility handled the situation much better than I expected, though it is unable to distinguish mater lectiones from consonantal vavs. However, this might be something that BabelPad normalization + locale based collation together might be able to overcome. I was told by an Israeli over IRC that the he_IL unix locale did count the vowels when sorting, but this appears to not be the case! Perhaps he was using the BSD `sort` utility on OS X, which is quite out of date.

sorting based on code points is, of course, as horrible as expected.
